In [2]:
# 读取和存储

import torch
from torch import nn

x = torch.ones(3)
torch.save(x, "x.pt")

In [3]:
x2 = torch.load("x.pt")
print(x2)

tensor([1., 1., 1.])


In [4]:
y = torch.zeros(4)
torch.save([x,y],"xy.pt")

xy_list = torch.load("xy.pt")

In [5]:
torch.save({"x":x,"y":y},"xy_dict.pt")
xy = torch.load("xy_dict.pt")
print(xy)

{'x': tensor([1., 1., 1.]), 'y': tensor([0., 0., 0., 0.])}


In [10]:
# 读写模型
# 在pytorch中，Module的可学习参数（即权重和偏差），模块模型包含在参数中，state_dict是一个从参数名称隐射的参数Tensor的字典对象
class MLP(nn.Module):
  def __init__(self):
    super(MLP,self).__init__()
    self.hidden = nn.Linear(3,2)
    self.act = nn.ReLU()
    self.output = nn.Linear(2,1)
  
  def forward(self,x):
    a = self.act(self.hidden(x))
    return self.output(a)

net = MLP()
net.state_dict()

OrderedDict([('hidden.weight',
              tensor([[ 0.5194,  0.1144, -0.3850],
                      [ 0.0532, -0.4177, -0.3763]])),
             ('hidden.bias', tensor([-0.5559, -0.1268])),
             ('output.weight', tensor([[-0.5575, -0.6112]])),
             ('output.bias', tensor([0.0408]))])

In [11]:

optimizer = torch.optim.SGD(net.parameters(),lr = 0.001, momentum = 0.9)
optimizer.state_dict()

{'state': {},
 'param_groups': [{'lr': 0.001,
   'momentum': 0.9,
   'dampening': 0,
   'weight_decay': 0,
   'nesterov': False,
   'maximize': False,
   'foreach': None,
   'differentiable': False,
   'params': [0, 1, 2, 3]}]}

In [13]:
X = torch.randn(2,3)
Y = net(X)

PATH = "./net.pt"
torch.save(net.state_dict(), PATH)

net2 = MLP()
net2.load_state_dict(torch.load(PATH))
Y2 = net2(X)
Y2 == Y

tensor([[True],
        [True]])