In [1]:
# GPU 计算

import torch
from torch import nn

torch.cuda.is_available()

True

In [2]:
torch.cuda.device_count()

1

In [3]:
torch.cuda.current_device()

0

In [4]:
torch.cuda.get_device_name()

'NVIDIA GeForce GTX 1650'

In [5]:
x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [7]:
x = x.cuda(0)
x

tensor([1, 2, 3], device='cuda:0')

In [8]:
x.device

device(type='cuda', index=0)

In [9]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [10]:
x = torch.tensor([1,2,3],device=device)

In [11]:
x

tensor([1, 2, 3], device='cuda:0')

In [12]:
# 如果对在GPU上的数据进行运算，那么结果还是存放在GPU上
y = x**2
y
# 存储在不同位置中的数据是不可以直接计算的
# 存放在CPU上的数据不可以直接与存放在GPU上的数据进行运算，位于不同的GPU上的数据也是不能直接进行计算的

tensor([1, 4, 9], device='cuda:0')

In [13]:
# 在GPU上的数据
net = nn.Linear(3,1)
list(net.parameters())[0].device

device(type='cpu')

In [14]:
# 转换到GPU上
net.cuda()
list(net.parameters())[0].device


device(type='cuda', index=0)

In [ ]:
# 我们需要保证模型输入的Tensor和模型都在同一设备上，否则会报错