# 卷积神经网络（convolutional neural network)

In [3]:
import torch
from torch import nn


def corr2d(X, K):
  h, w = K.shape
  Y = torch.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1))

  for i in range(Y.shape[0]):
    for j in range(Y.shape[1]):
      Y[i, j] = (X[i : i + h, j : j + w] * K).sum()
  return Y


In [4]:
X = torch.tensor([[0,1,2],[3,4,5],[6,7,8]])
K = torch.tensor([[0,1],[2,3]])

corr2d(X,K)


tensor([[19., 25.],
        [37., 43.]])

In [8]:
class Conv2D(nn.Module):
  def __init__(self,kernel_size):
    super(Conv2D,self).__init__()
    self.weight = nn.Parameter(torch.randn(kernel_size))
    self.bias = nn.Parameter(torch.randn(1))
  
  def forward(self, x):
    return corr2d(x, self.weight) + self.bias

In [5]:
# 图像中的物体边缘检测
X = torch.ones(6,8)
X[:,2:6] = 0
X

tensor([[1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.]])

In [6]:
K = torch.tensor([[1,-1]])
Y = corr2d(X,K)
Y

tensor([[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.]])

In [9]:
conv2d = Conv2D(kernel_size=(1, 2))
setp = 20
lr = 0.01
for i in range(setp):
  Y_hat = conv2d(X)
  l = ((Y_hat - Y) ** 2).sum()
  l.backward()

  # 梯度下降
  conv2d.weight.data -= lr * conv2d.weight.grad
  conv2d.bias.data -= lr * conv2d.bias.grad

  # 梯度清0
  conv2d.weight.grad.fill_(0)
  conv2d.bias.grad.fill_(0)

  if (i + 1) % 5 == 0:
    print("Setp %d, loss %.3f " % (i + 1, l.item()))


Setp 5, loss 5.909 
Setp 10, loss 1.039 
Setp 15, loss 0.222 
Setp 20, loss 0.054 
